[3537532] Add Single Directory Component validation. (#684)
Co-authored-by: Joshua Fernandes <“joshua.1234511@yahoo.in”>
Co-authored-by: rgaunt <richard.gaunt@protonmail.com>

diff --git a/.github/workflows/test-drupal.yml b/.github/workflows/test-drupal.yml
--- a/.github/workflows/test-drupal.yml
+++ b/.github/workflows/test-drupal.yml
@@ -52,6 +52,21 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Run ct_dev kernel tests
+        run: vendor/bin/phpunit -c ../ct_dev/phpunit.xml.dist
+        working-directory: tools/sdc/build
+
+      - name: Validate SDC components
+        run: |
+          output=$(vendor/bin/drush ct_dev:validate-component-definition ../web/themes/custom/civictheme_sdc/components 2>&1)
+          echo "${output}"
+          if echo "${output}" | grep -E -q '\b(failed|Failed)\b'; then
+            echo "Component validation failed"
+            exit 1
+          fi
+        working-directory: tools/sdc/build
+        continue-on-error: ${{ vars.CI_DRUPAL_SDC_VALIDATE_IGNORE_FAILURE == '1' }}
+
       - name: Lint SDC components
         run: |
           output=$(vendor/bin/drush sdc-devel:validate civictheme_sdc 2>&1)
